### ISSUE TITLE
Sqlite3 database self-destructs if app aborted with ^C 

### ISSUE THREAD

**Issue by regulatre** [peter-wangxu/persist-queue#58] opened 2018-07-16 16:26 UTC
scenario: using persistqueue.SQLiteAckQueue, a few messages in queue but not yet consumed, process is terminated with SIGTERM or ^C. Subsequent attempts to run the app and use .get() to pull a message off the queue are met with the exception `OperationalError: Could not decode to UTF-8 column 'data' with text '?}q'` which is because the sqlite3 database contains one or more rows with invalid data. 

My quick and dirty solution: 
```
--- Delete all the rows where the data field is less than 10 characters. My normal payload length is over 250 bytes so this is very effective at blowing away those rows with corrupted data. 
CREATE VIEW view_lengthchecker AS select *,LENGTH(data) 'ld' from ack_queue_default WHERE ld < 10;
DELETE FROM ack_queue_default WHERE _id IN (SELECT _id FROM view_lengthchecker);
```

**Comment by regulatre** [comment] 2018-07-16 17:30
In terms of the best way to overcome this sort of corruption we have to think of a way to handle it gracefully and such that it doesn't block the message from being queued or dequeued. 

Ideally, we would want the sqlite3 library to more gracefully shut down and not corrupt the database in the event of an unexpected shutdown (it should catch the signal and run a cleanup function before going down) but I don't think we would get much traction with this route. 

On the other hand we can work within this project and add the necessary self-healing logic, to repair the database in the event that the situation arises. The overly simplistic code that I offered above may work for this failure scenario but perhaps not others - if there are others we should roll those into whatever we come up with. 

so.. a few ideas off the top of my head

1. On startup, run database consistency checks, and self-healing checks, from within the library
2. Add exception handling to get() put() and others as needed, to more quickly detect when things have started to go wrong, then move to isolate the problem, minimize it, and cut it out (delete bad records).

**Comment by EverWinter23** [comment] 2018-08-03 06:30
@peter-wangxu Does this only affect SQLiteAckQueue or does it affect other Qs as well which make use of the SQLiteAckQueue or database.

**Comment by peter-wangxu** [comment] 2018-08-31 07:55
Thanks for the feedback;
@regulatre @EverWinter23 The `get` and `put` itself are atomic anyway, but with regard to the filesystem, the mount option should also be taken into account.

Can you please share you mount option of queue file? 
Thanks

**Comment by peter-wangxu** [comment] 2018-09-23 15:07
Sorry for my late response
@regulatre @EverWinter23 
The issue is easy to reproduce. This should be a bug for `SQLiteAckQueue` only, it's not reproducible for other sqlite queues.

@dexter-xiong can you please take a quick look firstly?

Thanks
Peter

**Comment by peter-wangxu** [comment] 2018-09-25 14:47
This should be resolved by GH-66

**Closed by peter-wangxu** 2018-09-25 14:47 UTC
Labels: bug, sqlite3
