### ISSUE TITLE
Issues where persistqueue is not thread safe

### ISSUE THREAD

**Issue by gleblanc1783** [peter-wangxu/persist-queue#50] opened 2018-05-24 15:38 UTC
Hi, I am using Persist-Queue in a multi-threaded environment where queue objects (UniqueQ) are being added and removed multiple times per second. Sometimes, I am seeing different threads obtain the same Queue object (see below):

```
2018-05-23 19:16:16,960 DEBUG    [root] Processing /data/x/x/x/ready/x-csv.tbz2
2018-05-23 19:16:16,960 DEBUG    [root] Processing /data/x/x/x/ready/x-csv.tbz2
```

As you can see, they are pulling from the same queue but getting the same file (sanitized paths, of course).

Here's how I am creating my queue object: 

`q = persistqueue.UniqueQ(queue_path, auto_commit=True)`

Using:

`file_to_process = queue.get()`

persist-queue==0.3.5

**Comment by peter-wangxu** [comment] 2018-05-25 00:13
What's the OS and Python version?

**Comment by peter-wangxu** [comment] 2018-05-26 08:28
I added one test of multiple readers in multi-threading mode, but no luck, not able to reproduce.

You can run the all the tests via:
```
tox
```
to verify if it's related to sqlite3 in your environment.


BTW, can you please share your versions as below:

```python
>>> sqlite3.sqlite_version
'3.23.1'
>>> sqlite3.version
'2.6.0'
```

**Comment by gleblanc1783** [comment] 2018-05-29 11:40
Hi! Sure thing. 

OS is Oracle Linux 7.4
Python version is 2.7.5

```
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'
>>> sqlite3.version
'2.6.0'
>>>
```

It looks like your SQLite3 version is newer, let me try upgrading that, testing it and reporting back. Also - I am going to upgrade to Python 3.6 anyways, will also try that.

**Comment by gleblanc1783** [comment] 2018-05-31 13:55
Hi, I have upgraded my SQLite on my Operating system and I'm seeing the same issue. I will try the `tox` today and see what I can replicate.

**Comment by peter-wangxu** [comment] 2018-06-01 02:12
Bad news, if possible, you could share how you use the queue in your program, pseudo-code shall be enough.

**Comment by gleblanc1783** [comment] 2018-06-01 13:30
Absolutely, here it goes.

### module1.py (Only 1 of these runs at a single time):
1. Gathers filenames from a directory, adds them to a UniqueQ:

```
def add_to_queue(q, filename):
    try:
        q.put(filename)
    except Exception as e:
        print(str(e))
```

### module2.py (Up to 8 of these are running at a single time via Apache Airflow)
1. Open the queue
2. Iterate over the queue, if there are still entries (queue.size > 0) continue popping until 0 or it meets it's worker maximum
```
while True: # Keep processing until complete
            if queue.size == 0:
                logger.info("Queue is empty. Inserting data then exit.")
                insert_data()
                sys.exit(0)
            else:
                if worker_tracker >= worker_limit:
                    logger.debug("Worker Limit met. Inserting data then exiting.")
                    insert_data()
                    sys.exit(0)
                else:
                    file_to_process = queue.get()
                    logger.debug("Processing {}".format(file_to_process)) # Here is where I see duplicates per worker 
                    process_files(file_to_process, to_dir, appliance_type, table_map)
                    worker_tracker += 1
```

Both queues are instanciated by doing the below:

`q = persistqueue.UniqueQ(queue_path, auto_commit=True)
`

**Comment by gleblanc1783** [comment] 2018-06-01 13:35
I've noticed that it *only* happens when two separate threads are trying to pop the queue at the same milisecond:

2018-06-01 13:20:**29,044** DEBUG    [2d058a8a-df97-4551-af4b-c91e920de18e] Processing ... 180601081806454213052-csv.tbz2
2018-06-01 13:20:**29,044** DEBUG    [3f94ffa7-45a4-41d0-a96f-ede1af5dacb6] Processing ... 180601081806454213052-csv.tbz2

The UUIDs are generated per thread for debug purposes.

**Comment by peter-wangxu** [comment] 2018-06-01 14:13
Are the producer and the workers in separate processes or same process?

If in one same process, I suggest creating one queue and share it between producer and consumes.

If not, I tend to think it's somehow by design, the synchronization only works within one process.

**Comment by gleblanc1783** [comment] 2018-06-04 12:28
Oh great! I will test this today - thanks so much.

**Comment by peter-wangxu** [comment] 2018-06-06 02:04
@gleblanc1783 any progress till now?

**Comment by peter-wangxu** [comment] 2018-06-17 12:39
I tend to think it's solved by add `multithreading=True`, closing it now.

**Closed by peter-wangxu** 2018-06-17 12:39 UTC
